#!/usr/bin/env bash
# Configures an Ubuntu server with the following requirements:
# - localhost resolves to 127.0.0.2
# - facebook.com resolves to 8.8.8.8

awk '
/127\.0\.0\.1.*localhost/ { gsub(/127\.0\.0\.1/, "127.0.0.2"); print; next }
/facebook\.com/ { print "8.8.8.8 facebook.com"; next }
{ print }
END { 
    if (!seen_facebook) print "8.8.8.8 facebook.com" 
}
/facebook\.com/ { seen_facebook = 1 }
' /etc/hosts > /tmp/hosts_new && cp /tmp/hosts_new /etc/hosts